### ISSUE TITLE
Tips for fixing Unhandled exception

### ISSUE THREAD

**Issue by jenskastensson** [nabbl/node-red-contrib-google-home-notify#2]
Hello and thank you this very nice thing!

I've noticed that if the ip number is wrong (DHCP or typo) the node dies with unhandled exception.

Can you give me a hint where to look for this, maybe you have an idea how to fix it?
I'm running it with node js v4, so I've done some very minor modifications of your code, I think it is not related.
Thanks in advance
Jens

29 Sep 15:03:27 - [info] Started flows
Error: connect ETIMEDOUT 192.168.1.31:8009
29 Sep 15:03:29 - [red] Uncaught Exception:
29 Sep 15:03:29 - Error: connect ETIMEDOUT 192.168.1.31:8009
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)

**Comment by nabbl** [comment]
Well that seems to be just bad error handling on my side. I am trying to fix it for the newest version.

**Comment by torinnguyen** [comment]
I've fixed this in a pull request & a huge improvement. Please merge.  #3

**Comment by nabbl** [comment]
thx. merged and closed :)

**Comment by nabbl** [comment]
You can download version 0.0.4 from NPM which contains the fixes and enhancement

**Comment by jenskastensson** [comment]
Hello and thanks for the update. 
Unfortunately, it still crashes with NodeJS v4 if the IP of the GH device is invalid. (there's only v4 on the platform I'm using). The crash happens 30-60 sec after the text was sent.
Maybe you can give me some hints on how to prevent the crash, I dont mind 'ugly' fixes like adding try catch or to add a test of the tcp connection before invoking the real action.

Error: connect ETIMEDOUT 192.168.1.31:8009
24 Oct 09:37:49 - [red] Uncaught Exception:
24 Oct 09:37:49 - Error: connect ETIMEDOUT 192.168.1.31:8009
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)

**Comment by torinnguyen** [comment]
Unfortunately this error lies deep inside one of the dependency node modules, which I have not figured out exactly yet.

The quick workaround is to use Exception node built-in in NodeRED.
You can find more details here
https://developer.ibm.com/recipes/tutorials/nodered-exception-handling-framework/#r_step5

I'm not sure if it's possible to perform self catching within this node. I'll do some research.

**Comment by jenskastensson** [comment]
Thanks for the idea! I tried it immediately but neither Catch "All Nodes" or Catch "selected nodes=GoogleNotify" did the job. Too bad.
What do you think about the not-very-elegant solution to test the IP before continuing? (where and which api's)
Jens

**Comment by jenskastensson** [comment]
Do you mind re-opening this issue , it is still a problem with the crash if the IP is incorrect.

**Comment by nabbl** [comment]
Well it is not closed. I closed the duplicate one which had less info.
